- set_fact:
    ldap_base_dn: "{% for seg in ldap_domain.split('.') %}dc={{ seg }}{% if not loop.last %},{% endif %}{% endfor %}"
    _ldap_dir_backup: "{{ ldap_dir_backup }}/{{ ansible_host }}"
  tags: always

- debug:
    msg: |
      ansible_facts['nodename']: {{ ansible_facts['nodename'] }}
      ansible_fqdn: {{ ansible_fqdn }}
      ansible_host: {{ ansible_host }}
      ldap_dir_backup: {{ _ldap_dir_backup }}

#- meta: end_play

- name: Ensure ldap directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ ldap_dir_certs }}"
  - "{{ ldap_dir_data }}"
  - "{{ ldap_dir_config }}"
  - "{{ _ldap_dir_backup }}"

- name: Render Docker Compose template
  template:
    src: "docker-compose/{{ openldap_image }}-docker-compose.yaml.j2"
    dest: "{{ ldap_dir_config }}/../docker-compose.yaml"
    backup: yes

- name: Execute docker-compose
  command: docker-compose --no-ansi -p {{ docker_compose_project }} -f {{ ldap_dir_config }}/../docker-compose.yaml {{ docker_compose_command }}
  register: output

- debug:
    var: output

- assert:
    that:
    - "not output.rc"
